### ISSUE TITLE
Close Inventory

### ISSUE THREAD

**Issue by franciscopereira2004** [0rangeFox/es_extended#1]
Hi, i can close mu inventory, any can help-me? Ty for all

**Comment by 0rangeFox** [comment]
> Hi, i can close mu inventory, any can help-me? Ty for all

Sorry, didn't understand your error, can you provide more information please? Thanks.

**Comment by franciscopereira2004** [comment]
Hi man, you have a discord to be more easy communication with you?

**Comment by 0rangeFox** [comment]
> Hi man, you have a discord to be more easy communication with you?

Hey, my discord is literally on README.md, from [here](https://github.com/0rangeFox/es_extended).
