### ISSUE TITLE
Mistake that you made in Markers and Blips xD

### ISSUE THREAD

**Issue by BlackZon77** [0rangeFox/es_extended#2]
es_extended/client/modules/blip.lua:43 > 
ESX.Blips.Register(tempBlip) to this ESX.UI.Blips.Register(tempBlip)

es_extended/client/modules/marker.lua:80 > 
ESX.Markers.Enter(lastMarker) to this ESX.UI.Markers.Enter(lastMarker)

es_extended/client/modules/marker.lua:84 > 
ESX.Markers.Exit() to this ESX.UI.Markers.Exit()

**Comment by 0rangeFox** [comment]
> es_extended/client/modules/blip.lua:43 >
> ESX.Blips.Register(tempBlip) to this ESX.UI.Blips.Register(tempBlip)
> 
> es_extended/client/modules/marker.lua:80 >
> ESX.Markers.Enter(lastMarker) to this ESX.UI.Markers.Enter(lastMarker)
> 
> es_extended/client/modules/marker.lua:84 >
> ESX.Markers.Exit() to this ESX.UI.Markers.Exit()

Where you saw that code? What you said, is already in repository.

**Comment by 0rangeFox** [comment]
Pardon me, you was right, i was blinded on that day and didn't fixed the look on that lines. But honestly, thanks for your time and the fix.
